//
//  NewsListWorkerTests.swift
//  BlognoneDemo
//
//  Created by Suraphan 'Rawd' Laokondee on 6/23/2560 BE.
//  Copyright (c) 2560 Suraphan 'Rawd' Laokondee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import BlognoneDemo
import XCTest

class NewsListWorkerTests: XCTestCase {
  // MARK: - Subject under test
  
  var sut: NewsListWorker!
  
  // MARK: - Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupNewsListWorker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupNewsListWorker() {
    sut = NewsListWorker()
  }
  
  // MARK: - Test doubles
  
  // MARK: - Tests
  
  func testSomething() {
    // Given
    
    // When
    
    // Then
  }
}
