//
//  NewsListConfigurator.swift
//  BlognoneDemo
//
//  Created by Suraphan 'Rawd' Laokondee on 6/23/2560 BE.
//  Copyright (c) 2560 Suraphan 'Rawd' Laokondee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension NewsListViewController: NewsListPresenterOutput {
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    router.passDataToNextScene(segue: segue)
  }
}

extension NewsListInteractor: NewsListViewControllerOutput {
}

extension NewsListPresenter: NewsListInteractorOutput {
}

class NewsListConfigurator {
  // MARK: - Object lifecycle
  
  static let sharedInstance = NewsListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: NewsListViewController) {
    let router = NewsListRouter()
    router.viewController = viewController
    
    let presenter = NewsListPresenter()
    presenter.output = viewController
    
    let interactor = NewsListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
