//
//  NewsListInteractor.swift
//  BlognoneDemo
//
//  Created by Suraphan 'Rawd' Laokondee on 6/23/2560 BE.
//  Copyright (c) 2560 Suraphan 'Rawd' Laokondee. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol NewsListInteractorInput {
  func fetchNewsFeed(request: NewsList.RequestNewsFeed.Request)
}

protocol NewsListInteractorOutput {
  func presentRequestNewsFeed(response: NewsList.RequestNewsFeed.Response)
}

class NewsListInteractor: NewsListInteractorInput {

  var output: NewsListInteractorOutput!
  var worker: NewsListWorker! = NewsListWorker()
  
  // MARK: - Business logic
  
  func fetchNewsFeed(request: NewsList.RequestNewsFeed.Request) {
    // 3 demo fetchNewsFeed
    // NOTE: Create some Worker to do the work
    worker.fetchNewsFeed {[weak self] (newsList) in
      // NOTE: Pass the result to the Presenter
      
      let response = NewsList.RequestNewsFeed.Response(newsList: newsList)
      self?.output.presentRequestNewsFeed(response: response)
    }
  }
}
